mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from content import urls, views
from django.conf.urls.static import static
from django.conf import settings
from content import views as content_views
from dashboard import views as dashboard_views

urlpatterns = [
    url(r'^$', dashboard_views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include('accounts.urls')),
    url(r'fms/', include('content.urls')),

    url(r'^type/add/$', views.type_add, name='type_add'),
    #url(r'^type/del/(?P<id>[a-zA-Z0-9]{32,32})/$', views.type_del, name='type_del'),
    url(r'^type/del/(?P<id>\d+)/$', views.type_del, name='type_del'),
    
    url(r'^get/email/$', views.get_email, name='get_email'),
    url(r'^send/emails/$', views.send_mails, name='send_mails'),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^images/upload/$', content_views.upload_images, name='upload_images'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    


'''
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    
    url(r'^', include('account.urls')),
    #url(r'^$', RedirectView.as_view(url='/account/index/', query_string=True)),
    #url(r'^$', RedirectView.as_view(url='/login/', query_string=True)),
]
'''

mysite/content/models.py
#-*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import AbstractUser, Permission, Group
from django.conf import settings
from accounts.models import MyUser, Project
from .storage import images_storage
import uuid

class Type(models.Model):
    """ 故障类型 """
    fms_type = (
        ('0','运营商故障'),
        ('1','机房故障'),
        ('2','程序故障')
    )
    name = models.CharField(choices=fms_type , max_length=255, verbose_name=u"故障类型", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        permissions = (
            ("update_type", ("更新故障类型")),
            ("del_type", ("删除故障类型")),
        )
        default_permissions = ()


class Content(models.Model):
    """ 故障表 """
    
    fms_level = (
        (0, u"非常严重"),
        (1, u"严重"),
        (2, u"中等"),
        (3, u"一般"),
        (4, u"无影响"),
    )
    fms_status = (
        (0, u"处理中"),
        (1, u"已恢复"),
        (2, u"改进中"),
        (3, u"已完结"),
    )
    fms_improve = (
        (0, u"开发"),
        (1, u"运维"),
        (2, u"机房"),
        (3, u"网络运营商"),
        (4, u"第三方"),

    )
    id = models.UUIDField(blank=True, primary_key=True, auto_created=True, default=uuid.uuid4)
    title = models.CharField(max_length=255, verbose_name=u'故障标题', unique=True)
    effect = models.TextField(verbose_name=u'故障现象', null=True, blank=True)
    content = models.TextField(verbose_name=u'故障分析', null=True, blank=True)
    reasons = models.TextField(verbose_name=u'故障原因', null=True, blank=True)
    solution = models.TextField(verbose_name=u'解决方案', null=True, blank=True)
     
           
    author = models.ForeignKey(MyUser, verbose_name=u'创建者', on_delete=models.PROTECT, null=True, blank=True)
    type = models.ForeignKey(Type, verbose_name=u'故障类型',  on_delete=models.PROTECT, null=True, blank=True)
    project = models.ForeignKey(Project, verbose_name=u'影响项目', on_delete=models.PROTECT, null=True, blank=True)
     
    level = models.IntegerField(choices=fms_level, verbose_name=u'故障级别', default=0)
    status = models.IntegerField(choices=fms_status, verbose_name=u'故障状态', default=0)
    improve = models.IntegerField(choices=fms_improve, verbose_name=u'主导改进', default=0)
        
    start_time = models.DateTimeField(verbose_name=u'开始时间', null=True, blank=True)
    end_time = models.DateTimeField(verbose_name=u'结束时间', null=True, blank=True)
    ctime = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        permissions = (
            ("get_content", ("查看故障列表")),
            ("detail_content", ("故障详情")),
            ("add_content", ("添加故障")),
            ("edit_content", ("编辑故障")),
            ("del_content", ("删除故障")),
        )
        default_permissions = ()
        
        verbose_name = u"故障表"
        verbose_name_plural = verbose_name



class ZbxContent(models.Model):

    fms_status = (
        (0, u"处理中"),
        (1, u"已恢复"),
        (2, u"改进中"),
        (3, u"已完结"),
    )

    id = models.UUIDField(blank=True, primary_key=True, auto_created=True, default=uuid.uuid4)
    eventid = models.IntegerField(unique=True, verbose_name=u'事件ID')
    title = models.CharField(max_length=255, verbose_name=u'故障简述')
    host = models.CharField(max_length=120, verbose_name='故障服务器Top10', null=True)
    author = models.CharField(max_length=10, default='ZABBIX', verbose_name=u'ZBX用户')
    level = models.CharField(max_length=60, verbose_name=u'故障级别')
    type = models.CharField(max_length=120, verbose_name=u'zbx应用集', blank=True, null=True)
    project = models.CharField(max_length=255, verbose_name=u'ZBX主机组')
    effect = models.TextField(blank=True, verbose_name=u'故障影响', null=True)
    reasons = models.TextField(blank=True, verbose_name=u'故障原因', null=True)
    solution = models.TextField(blank=True, verbose_name=u'解决方案', null=True)
    status = models.CharField(max_length=60, verbose_name=u'处理状态', default=u'未恢复')
    improve = models.CharField(max_length=10, default=u'运维', verbose_name=u'主导改进')
    content = models.TextField(blank=True, verbose_name=u'故障分析')
    start_time = models.DateTimeField(verbose_name=u'开始时间')
    end_time = models.DateTimeField(verbose_name=u'结束时间', null=True, blank=True)
    ctime = models.DateTimeField(auto_now_add=True, verbose_name=u'创建时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = u"故障表"
        verbose_name_plural = verbose_name


class Images(models.Model):

    url = models.ImageField(upload_to='img/%Y/%m/%d', blank=True, null=True, storage=images_storage())
    create_time = models.DateTimeField(auto_now_add=True, blank=True, null=True)

mysite/templates/fms/fms.html
{% extends 'base/base_site.html' %} 
{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/plugins/chosen/chosen.css">
{{ block.super}}
<style type="text/css">
  .form-control-bulk-import {
    width:200px;
    display:inline;
}
</style>

{% endblock %}
{% block content %}
<div class="ibox-title">
  <h5>故障列表</h5>
</div>
<div class="ibox-content">
  <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline">
    <div class="row">
      <div class="col-sm-8">
        <div class="dataTables_length" id="DataTables_Table_0_length" style="margin-bottom:15px;">
        {{request.perms.List}}
          <a href={% url 'fms_add'%} class="btn btn-sm btn-success"><i class="fa fa-plus"></i> 添加故障</a>
         <!-- <button id="bulk_update" class="btn btn-sm btn-primary"><i class="fa fa-refresh"></i> 批量更新</button> 
          <button id="bulk_delete" class="btn btn-sm btn-danger"><i class="fa fa-recycle"></i> 批量删除</button> 
         -->
          <!-- <a class="btn btn-sm btn-info" data-toggle="modal" data-target="#bulk_import"><i class="fa fa-arrow-up"></i> 批量导入</a> -->
          <input type="text" placeholder="搜索: 故障类型、影响项目" id="search" class="form-control input-sm" style="width:280px;">
        </div>
      </div>
    </div>
    <table class="table table-striped table-bordered table-hover dataTables-example dataTable dtr-inline" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
      <thead>
        <tr role="row">
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">ID</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >故障简述</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >故障级别</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >故障类型</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >影响项目</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >主导改进</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >持续时间</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >故障状态</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >创建者</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >创建时间</th>
          <th  tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" >操作</th>

        </tr>
      </thead>
      <tbody id="content">
      {% include 'fms/fms_table.html'%}
      </tbody>
    </table>
<div class="modal inmodal" id="editor" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-body" style="margin-top: 15px">
                <form class="form-horizontal" id="jquery_post_from" method="post" action="">
                    {% csrf_token %} 
                    <!-- <input type="hidden" name="csrfmiddlewaretoken" value="kRaVIjNCyIT8a9V7EzT7ffeSH3avSyg7"> -->
                    <div class="form-group">
                        <label class="control-label col-sm-3 col-lg-3" for="id_explanation">选择邮件组</label>
                        <div class=" col-sm-8 col-lg-8 ">
                            <select data-placeholder="选择权限" class="chosen-select" multiple="" style="width: 350px; display: none;" tabindex="-1" id="email">
                            </select>
                        </div>
                    </div>
                </form>
                <div style="text-align:center">
                    <button class="btn btn-white" type="cancel"> 重置 </button>
                    <button class="btn btn-primary btn-commit"> 提交 </button>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'common/paginator.html'%}
</div>
{% endblock %}
{% block javascripts %}
{{ block.super}}
<script src="/static/js/plugins/chosen/chosen.jquery.js" type="text/javascript"></script>
<!-- 实时搜索 -->
<script type="text/javascript">
    var flag;
    function func1() {
        clearTimeout(flag);
        flag = setTimeout(function() {
          data();
        }, 200);

    }
    function  data(){
        search = $('#search').val();
        $.ajax({
          url: '{% url 'fms_search' %}',
          type: 'GET',
          dataType: 'html',
          data: {"search":search},
          success: function(data){
          $("#content").html(data);
          }
        });
    }
    $("#search").keyup(function(event){
      func1();
    });
</script>
<!-- 实时搜索End -->

<script type="text/javascript">
function resetChosen() {
    var config = {
        '.chosen-select': {
            width: "100%"
        },
        '.chosen-select-deselect': {
            allow_single_deselect: true
        },
        '.chosen-select-no-single': {
            disable_search_threshold: 10
        },
        '.chosen-select-no-results': {
            no_results_text: 'Oops, nothing found!'
        },
        '.chosen-select-width': {
            width: "100%"
        },

    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
    $('#email').trigger("chosen:updated");
}

</script>
<script type="text/javascript">
  function reset() {
        $('#email').val("");
    }

String.prototype.bool = function() { 
    return (/^true$/i).test(this); 
};
</script>

<script type="text/javascript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
    $('.btn-email').on('click',function(event){
        var btn = $(event.target);
        var row = btn.data('row').split('|');
        var id = row[0];
        var cauthor = row[1];
        var nuser = "{{ request.user.fullname }}";
        if( cauthor == nuser || "{{ request.user.is_superuser }}".bool() ){
          $("a").attr("data-target","#editor");
          $("#email").empty();
          $.get("{% url 'get_email' %}",function(data,status){
                if(data.length >0 && status == "success"){
                            $.each(jQuery.parseJSON(data),function(k,v){
                                var  obj = document.getElementById("email");
                                var  op = new Option(v.name,v.name)
                                obj.add(op);
                            })
                }
                resetChosen();

         });

        $('.btn-commit').on('click',function(){
            var email_group =  $('#email').val();
            $.ajax({
                type: "POST",
                url: "{% url 'send_mails' %}",
                async: true,
                data: {"content_id":id,"email_group":JSON.stringify(email_group)},
                success: function(data,textStatus){
                      window.location.reload()
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                      alert(XMLHttpRequest.status);
                      alert(XMLHttpRequest.readyState);
                      alert(textStatus);
                },
            });
        });
        }
        else{
          $("a").removeAttr("data-target");
          alert("只有创建者才可以发送通知！");
        }
       
    });
</script>

{% endblock %}

mysite/templates/fms/fms_add.html
{% extends 'base/base_site.html' %} 
{% block css %}
{{ block.super}}
<link href="/static/css/animate.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">
<link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
<link rel="shortcut icon" href="https://pandao.github.io/editor.md/favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/static/js/plugins/editormd/editormd.css" />
<link rel="stylesheet" type="text/css" href="/static/js/plugins/datetimepicker/css/bootstrap-datetimepicker.css" />
<link href="/static/js/plugins/editormd/lib/katex/katex.min.css" rel="stylesheet">
<style type="text/css">
    .form_datetime {
        background-color: #eee;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        border: 1px solid #ccc;
        border-radius: 4px;
        padding: 4px 6px;
        font-size: 14px;
        line-height: 20px;
        text-align: center;
    }

    .table-condensed td {
        font-size: 10px;
    }
    .dow {
        font-size: 14px;
    }
    .switch {
        font-size: 14px;
      }

div:empty:before{
content: attr(placeholder);
color:#bbb;
}
div:focus:before{
content:none;
}
</style>

{% endblock %}
{% block content %}

<div class="row">
            <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>添加故障</h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config option 1</a>
                                    </li>
                                    <li><a href="#">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                            <div id="overview-content" class="ibox-content">
                            <form id="fmsform" method="POST" class="form-horizontal" action="{% url 'fms_add' %}">
                             
                            {% include 'fms/fms_content.html'%}
                            </form>
                            </div>
                    </div>
            </div>
{% endblock %}


{% block javascripts %}
{{ block.super}}
<script src="/static/js/plugins/datetimepicker/js/bootstrap-datetimepicker.js"></script>
<script src="/static/js/plugins/editormd/editormd.min.js"></script>
<script src="/static/js/plugins/editormd/lib/katex/katex.min.js"></script>

<script type="text/javascript">

    var Editor;
    var description = '请使用Markdown格式编写:\n19:54~20:19 萧山机房59.111.3.8受到SYN类型超132Gbps流量攻击\n20:02 机房安全部将此IP加入绿盟清洗设备\n20:25~21:08 萧山机房59.111.3.81受到SYN类型超137Gbps流量攻击\n1. 分析1 \n2. 分析2\n3. 分析3'
    $(function() {
                Editor = editormd("editormd", {
                width   : "80%",
                height  : 500,
                watch: 0,
                syncScrolling : true,
                flowChart: true,
                sequenceDiagram : true,
                taskList : true,
                tex  : true,
                imageUpload : true,//开启本地图片上传
                imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                imageUploadURL : "/images/upload",//图片上传地址
                placeholder: description,
                path    : "/static/js/plugins/editormd/lib/",

            });
        });
</script>

<script type="text/javascript">
    function toggleChevron(e) {
    $(e.target)
        .prev('.panel-heading')
        .find("i.indicator")
        .toggleClass('glyphicon-chevron-down glyphicon-chevron-up');
    }
    $('#accordion').on('hidden.bs.collapse', toggleChevron);
    $('#accordion').on('shown.bs.collapse', toggleChevron);

</script>


<script type="text/javascript">
    $("#collapse2").click(function(){
        Editor.resize();
         $(".CodeMirror").css("width","100%");
         $(".CodeMirror-sizer").css("top","20px");
         var text = document.getElementById('id_content').value;
         Editor.setValue(text);
    })
</script>

<script type="text/javascript">
    $(".form_datetime").datetimepicker({
        format: 'yyyy-mm-dd hh:ii:ss',
        minuteStep: 2,
        yearStart: 2017,
    });
    Date.prototype.Format = function (fmt) {  
        var o = {
            "M+": this.getMonth() + 1, //月份 
            "d+": this.getDate(), //日 
            "h+": this.getHours(), //小时 
            "m+": this.getMinutes(), //分 
            "s+": this.getSeconds(), //秒 
            "q+": Math.floor((this.getMonth() + 3) / 3), //季度 
            "S": this.getMilliseconds() //毫秒 
        };
        if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
        for (var k in o)
        if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
        return fmt;
    };
    date = new Date().Format("yyyy-MM-dd hh:mm:ss");
//默认显示当前时间
    $(".form_datetime").val(date);

</script>

{% endblock %}

mysite/templates/fms/fms_detail.html
{% extends 'base/base_site.html' %}
{% block css %}
{{ block.super}}
<link href="/static/js/plugins/editormd/lib/katex/katex.min.css" rel="stylesheet">
<style media="screen">
.m-table{
    border-collapse:collapse;
    margin: 0 auto;
    width: 80%;
}
.m-table td,th{
    border:0px solid #cccccc;
    padding: 5px;
    font-size: 14px;

}
.ibox-tools-new{
    float: right;
    margin-top: -30px;
}
.alert{
    padding:11px;
    background-color: #f5f5f5;
}
.ibox-content{
    padding-bottom:5%;
    min-width: 800px;
}
.ibox-title{
    min-width: 800px;
}

</style>
{% endblock%}

{% block content %}
<div class="ibox-title">
    <h3 style="margin-top:0px">故障报告: {{ content.title }}</h3>
    {% if request.user == content.author  or request.user.is_superuser %}
        <div class="ibox-tools-new">
            <a href=/fms/edit?id={{content.id}} class="btn btn-xs btn-success btn-edit">编辑</a>
        </div>
    {% endif %}
</div>

<div class="ibox-content">
    {% if content %}
    <div class="alert alert-info">
         <span class="alert-link">故障概述</span>
    </div>

    <table class="m-table">
        <tbody>
            <tr>
                <td><b>故障时间:</b></td>
                <td>{{content.start_time|date:"Y-m-d H:i"}}~{{content.end_time|date:"Y-m-d H:i"}}</td>

                <td><b>影响项目:</b></td>
                <td>{{content.project}}</td>

                <td><b>故障状态:</b></td>

                <td>
                    {% if content.author == 'ZABBIX' %}
                        {{content.status}}
                    {% else %}
                        {{content.get_status_display}}
                    {% endif %}

                </td>


            </tr>
            <tr>
                <td><b>故障等级:</b></td>
                <td>
                    {% if content.author == 'ZABBIX' %}
                        {{content.level}}
                    {% else %}
                        {{content.get_level_display}}
                    {% endif %}
                </td>
                <td><b>创建者:</b></td>
                <td>
                    {% if content.author == 'ZABBIX' %}
                        {{content.author}}
                    {% else %}
                        {{ content.author.fullname }}
                    {% endif %}

                </td>
                <td><b>主导改进方:</b></td>
                <td>
                    {% if content.author == 'ZABBIX' %}
                        {{content.improve}}
                    {% else %}
                        {{content.get_improve_display}}
                    {% endif %}

                
                </td>
            </tr>
            <tr>
                <td><b>故障类型:</b></td>
                <td>
                {% if content.type   %}
                    {{ content.type }}
                {% else %}
                    无  
                {% endif %}
                </td>
                <td><b>影响时间:</b></td>
                <td>{{ content.time }}</td>
                {% if content.author == 'ZABBIX' %}
                    <td><b>影响主机</b></td>
                    <td>{{ content.host }}</td>
                {% endif %}

            </tr>
        </tbody>
    </table>

    <div class="alert alert-info" style="margin-top:20px">
         <span class="alert-link">故障影响</span>
    </div>

    <table class="m-table">
        <tbody>
                <tr>
                <td>
                    <div id="editormd-effect">
                        <textarea style="display:none;">{{content.effect}}</textarea>
                    </div>

                </td>
                </tr>
        </tbody>
    </table>

    <div class="alert alert-info" style="margin-top:20px">
         <span class="alert-link">故障分析</span>
    </div>

    <table class="m-table">
        <tbody>
                <tr>
                <td>
                    <div id="editormd-content">
                        <textarea  style="display:none;">{{content.content}}</textarea>
                    </div>
                </td>
                </tr>
        </tbody>
    </table>

    <div class="alert alert-info" style="margin-top:20px">
         <span class="alert-link">故障原因</span>
    </div>

    <table class="m-table">
        <tbody>
                <tr>
                <td>
                    <div id="editormd-reasons">
                        <textarea style="display:none;">{{content.reasons}}</textarea>
                    </div>
                </td>
                </tr>
        </tbody>
    </table>

    <div class="alert alert-info" style="margin-top:20px,margin-bottom:20px">
         <span class="alert-link">解决方案</span>
    </div>

    <table class="m-table">
        <tbody>
                <tr>

                <td>
                    <div id="editormd-solution">
                        <textarea style="display:none;">{{content.solution}}</textarea>
                    </div>
                </td>                

                </tr>
        </tbody>
    </table>

    {% else %}
    <p style="text-align:center;color:#FF0000;font-weight:bold;">{{ error }}</p>
    {% endif %} 
</div>
{% endblock %}

{% block javascripts %}
{{ block.super}}
<script src="/static/js/plugins/editormd/lib/marked.min.js"></script>
<script src="/static/js/plugins/editormd/lib/prettify.min.js"></script>
<script src="/static/js/plugins/editormd/lib/raphael.min.js"></script>
<script src="/static/js/plugins/editormd/lib/underscore.min.js"></script>
<script src="/static/js/plugins/editormd/lib/sequence-diagram.min.js"></script>
<script src="/static/js/plugins/editormd/lib/flowchart.min.js"></script>
<script src="/static/js/plugins/editormd/lib/jquery.flowchart.min.js"></script>
<script src="/static/js/plugins/editormd/lib/katex/katex.min.js"></script>
<script src="/static/js/plugins/editormd/editormd.min.js"></script>

<script type="text/javascript">
    var  elements = ['#effect','#reasons','#solution'];
    $.each(elements,function(k,v){
        var temp = $(v).text().replace(/\n/g, '<br/>');
        $(v).html(temp);
    });

</script>

<script type="text/javascript">

  $(function() {
      var id = ["editormd-effect","editormd-reasons","editormd-content","editormd-solution"];
      $.each(id,function(k,v){
          var EditormdView = editormd.markdownToHTML(v, {
          htmlDecode      : "style,script,iframe",  
          emoji           : true,
          taskList        : true,
          tex             : true,  // 默认不解析
          flowChart       : true,  // 默认不解析
          sequenceDiagram : true,  // 默认不解析
          path    : "/static/js/plugins/editormd/lib/",
          autoLoadKaTeX: !1,
            });
         }); 
      });

</script>
{% endblock %}

mysite/templates/fms/fms_modal.html
<div class="modal inmodal" id="editor" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated fadeIn">
            <div class="modal-body">
                <form style="margin-top: 15px" class="form-horizontal" id="jquery_post_from" method="post" role="form" action="{% url 'type_add' %}">
                    {% csrf_token %}
                    <!-- <input type="hidden" name="csrfmiddlewaretoken" value="kRaVIjNCyIT8a9V7EzT7ffeSH3avSyg7"> -->
                    <div class="form-group">
                        <label class="control-label col-sm-2 col-lg-2" for="id_group_name">类型名称</label>
                        <div class=" col-sm-10 col-lg-10 ">
                            <input class="form-control" id="name" name="type_name" maxlength="100"  type="text">
                        </div>
                    </div>
                    <div style="text-align:center">
                            <button class="btn btn-white" type="cancel"> 重置 </button>
                            <button class="btn btn-primary btn-commit"> 提交  </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

mysite/templates/fms/fms_table.html
  {% load accounts_tag %}
        {% for i in content %}
        <tr class="gradeA odd" role="row">
          <td class="sorting_1">{{ i.id|split }}</td>
          <td><a href="/fms/detail/{{ i.id |uuid_to_str }}">{{ i.title }}</a></td>
          {% if i.author == 'ZABBIX' %}
            <td>{{ i.level }}</td>
            <td class="center">{{ i.type }}</td>
          {% else %}
            <td>{{ i.get_level_display }}</td>
            <td class="center">{{ i.type }}</td>
          {% endif %}

          <td class="center">{{ i.project }}</td>

          {% if i.author == 'ZABBIX' %}
            <td class="center">{{ i.improve }}</td>
          {% else %}
            <td class="center">{{ i.get_improve_display }}</td>
          {% endif %}
          <td class="center">{{ i.time }}</td>
          {% if i.author == 'ZABBIX' %}
              <td class="center">{{ i.status }}</td>
              <td class="center">ZABBIX</td>
          {% else %}
              <td class="center">{{ i.get_status_display }}</td>
              <td class="center">{{ i.author.fullname }}</td>
          {% endif %}

          <td class="center">{{ i.ctime }}</td>

          <td class="center">
           <a href=/fms/edit?id={{i.id|uuid_to_str}}  class="btn btn-xs btn-success btn-edit">编辑</a>
           <a class="btn btn-xs btn-primary btn-email" data-toggle="modal" data-target="#editor" data-row={{ i.id|uuid_to_str }}|{{ i.author.fullname }}>Email通知</a>
          </td>
        </tr>
        {% endfor %}